[package]
name = "serpent-ci-server"

version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5.16", features = ["ws", "headers"] }
tokio = { version = "1.21.2", features = ["full"] }
